---

version: "3"
services:
    agent:
        image: ssh-agent
        environment:
            PRIVATE: ${PRIVATE}
        volumes:
            - ./secret:/secret
    client:
        image: ssh-agent
        entrypoint: []
        links:
            - agent
        volumes:
            - ./secret:/secret
        command: ssh-add -l

